---
name: Repository Specific Checks

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}-ci
  cancel-in-progress: true

jobs:
  project_checks:
    name: Run project checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Set up poetry and install
        uses: ./.github/actions/setup-poetry

      - name: Pre-commit install
        run: make pre-commit

      - name: Run linting checks
        run: make lint

      - name: Run security checks
        run: make security-check

      - name: Check dependencies
        run: make dep-cve-check

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.9', '3.10', '3.11' ]
      fail-fast: false
    steps:
      - name: Check out
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Set up poetry and install
        uses: ./.github/actions/setup-poetry
        with:
          python-version: ${{ matrix.python-version }}

      - name: Run tests
        run: make test

  e2e-test:
    runs-on: 'ubuntu-24.04'
    permissions:
      contents: read
    steps:
      - name: Check out
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - uses: ./.github/actions/e2e-testing

  test-integration:
    runs-on: 'ubuntu-24.04'
    permissions:
      contents: read
    steps:
      - name: Check out
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - uses: ./.github/actions/test-integration
